<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Credito Uruguayo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>60</pageLoadTimeout>
   <pageLoadTimeoutDefault>false</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>163e0a1e-8e87-48e7-9869-d6763d9624a9</testSuiteGuid>
   <testCaseLink>
      <guid>d83cd7c2-f0e1-4fd1-b114-d2ffc75aabf4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/General/Generar Cedula Random</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>bd22fc6e-ceca-418a-be83-230f8fc02d13</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Marcas/CreditoUruguayo/CU - Flujo Web</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>63af670e-b565-4cb6-af39-e43c4312162c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7494e640-2641-4098-846d-f52d7442c10a</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2353907b-f60f-427c-b2ad-27130cb243ff</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>4f84a0b3-6d4e-4c68-9397-0b53348996db</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>0726d05d-d228-4097-9330-c3dc54eb744d</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>91171bb8-5d1b-4657-b98d-31e1470153ef</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>9f859e87-c0c7-4af6-8c2c-a98c1d67f3f2</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>0658e1c2-0a9f-4186-bfc2-8234e34a75ff</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/Logueo</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>3f174be5-21d3-4ef1-aa5e-9af9b5053774</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/SPI/Credito Uruguayo</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>040990dc-63e7-4b4d-b8e7-b7d549e6bd48</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/Credito Uruguayo/Activación Cuenta</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>27356878-6275-4502-9c39-52b8d3aaec63</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/Credito Uruguayo/Verificación</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee9dacc0-9017-4d94-800c-ce6141af932e</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>e44f3be3-3b4c-452b-9971-52f09086bc75</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/Credito Uruguayo/Desembolso</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>905ee884-05a3-475f-bcb4-c9550453516c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>fff355c6-32e4-490b-9d1d-9fe4b83a0588</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>ee053976-22bb-43cc-b522-cafbcad18d66</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>81de5486-92f1-447c-bc42-b3903f2cfe75</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
