<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>UinUin</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>b7ae4b97-fcbd-494f-8e4f-f1108809df23</testSuiteGuid>
   <testCaseLink>
      <guid>1ba4f940-fe2c-47ec-bc1f-5942717af2b5</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/General/Generar Cedula Random</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>d806967c-09de-4cc5-b875-c1f91daa900e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Marcas/UinUin/UU - Flujo Web</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>92cf14bb-af47-4757-a430-d7f2ae98048f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>410bc894-1db4-4696-ab8e-ecfbf61bea81</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>8377a43b-572c-46b2-be1e-63c57bb8e6c6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>2470f3bc-f4c5-4ee7-86af-55186c4e113f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6574be24-6516-4371-aa59-ffbd2bfb7b0e</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>6c5c35ff-41df-4e15-af98-b1e21150d4ae</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>b098a0e0-ebeb-4304-8f4f-c38631b2c82c</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/Logueo</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>95d68843-2d4c-4c2f-8876-252f3f027272</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/SPI/UinUin</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>8485ac62-f2d7-4777-a16c-ca2600d4b974</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Admin/UinUin/Creación Cuenta</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>a8eadcf9-612d-43c9-82e3-0ff4f6cdca84</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/UinUin/Verificación</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>dd5e3239-d4c5-4c52-a349-128a31fcba1f</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>f5bcdfa2-752f-441f-9197-27b199df544b</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/UinUin/Desembolso</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>d93c5e5c-dff0-4d23-8c37-3f5c074a67fc</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>08737d51-a4e2-4505-8cb0-fb7551f52c54</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>1e787a0f-35c6-4ff7-92ec-f05431612e96</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>7e5e78a3-88ee-4073-b407-b16d4363d3a6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
