<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>Volvé</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>bc84cb07-388f-4e55-add3-8b03216d5f50</testSuiteGuid>
   <testCaseLink>
      <guid>2c518224-42bf-4b18-99fc-1a003cf7e6e1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/General/Generar Cedula Random</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>5beb9576-98f6-44c5-9e35-79e2fb51daf1</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Marcas/Volve/VV - Flujo Web</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>85f4abcb-ffa5-4c32-866b-b41f948aa75b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>acb382c1-6651-46ae-abdb-3574c954ea55</variableId>
      </variableLink>
   </testCaseLink>
   <testCaseLink>
      <guid>2cb6153b-4339-4edb-b13b-51690c6cb734</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/Logueo</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>97a9560d-7701-4a2f-9631-22cc58a15c93</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/SPI/Volve</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>c9ee2d46-e93b-4be6-9895-1d8c40d80d3e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>false</isRun>
      <testCaseId>Test Cases/Admin/Volve/Activación Cuenta</testCaseId>
   </testCaseLink>
   <testCaseLink>
      <guid>b72fd20d-229e-4a8d-813d-0c5ee0e3c30e</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Admin/Volve/Desembolso</testCaseId>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>bcd45b69-b8a6-46aa-ac4e-6baf05dd189c</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>53b853a8-4843-469b-af16-55fe0e276db6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>61e56a81-5a60-4f01-9ff6-6846b4fe78a6</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>18badbaf-b7aa-48dc-b1bb-190d8b1d32e6</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
