<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_Localidad</name>
   <tag></tag>
   <elementGuidId>2edc8e96-69ee-417d-9469-056d1e1330bc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#locality</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//select[@id='locality']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>select</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locality</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>7</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Seleccione..Al Sur De Arroyo SacraAraújoArbolito (Totoral)Arroyo MaloArroyo NegroBeissoBella VistaCangüéCarumbéCasa BlancaCañada Del PuebloCerro ChatoChacras De PaysandúChacras De Paysandú NorteChacras De Paysandú SurChapicuyColonia Arroyo MaloColonia CangüéColonia JuncalColonia Las DeliciasColonia PaysandúColonia Santa BlancaColonia UruguayaConstanciaCosta De SacraCuchilla De BuricayupíCuchilla De FuegoCuchilla San JoséEl ChacoEl DuraznalEl EucaliptusEl HornoEl TarugoEstación PorvenirEtchemendiGallinalGuaviyú De QuebrachoGuayabosGuichónLa Lata Ruta 3 (Km. 375)La Paz (Ruta 3 Km. 346)La TentaciónLas FloresLas PalmasLorenzo GeyresMolles GrandeMorato (Tres Árboles)Nuevo PaysandúOrgorosoPalmar Del QuebrachoParada DaymánParada PanduleParada RivasPaso De Los CarrosPaysandúPerico MorenoPiedra SolaPiedras ColoradasPiñeraPorvenirPueblo AlonzoPueblo EsperanzaPueblo FederaciónPuntas De Arroyo NegroPuntas De BacacuáPuntas De BuricayupíPuntas De CanguePuntas De GualeguayPuntas De Las IsletasQuebrachoQueguay GrandeQueguayarRabónSan FranciscoSan FélixSan MauricioSan MiguelSanta KildaSauce De AbajoSauce Del BuricayupíSauce Del QueguaySotoTamboresTermas De AlmirónTermas De GuaviyúTomas PazTres BocasValdézVilla María (Tiatucura)Zeballos</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locality&quot;)</value>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//select[@id='locality']</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='__next']/div/div[2]/div/div[2]/form/select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Cuál es tu localidad?'])[1]/following::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Cuál es tu departamento?'])[1]/following::select[2]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Cuáles son tus ingresos mensuales?'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='¿Cuál es tu género?'])[1]/preceding::select[1]</value>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//select[2]</value>
   </webElementXpaths>
</WebElementEntity>
